on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [2.7, 3.5, 3.6, 3.7]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - run: |
        pip install .
        kitten --version
    - run: |
        pip install flake8
        flake8 --max-line-length 88 --ignore E203,E501
        python setup.py check -s
